apiVersion: apps/v1
kind: Deployment
metadata:
    name: test-ui
spec:
  replicas: 1
  selector:
      matchLabels:
        app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80

